### ISSUE TITLE
Huge binary size

### ISSUE THREAD

**Issue by cculpepper** [luojia65/example-gd32vf103#1]
Hello!

I'm trying to build from this project, and I am getting massive binary sizes. I just cloned it fresh, did a cargo build --release, and my binary size is huge:
`riscv64-unknown-elf-size target/riscv32imac-unknown-none-elf/release/example-gd32vf103 
   text	   data	    bss	    dec	    hex	filename
   1906	      0	  20480	  22386	   5772	target/riscv32imac-unknown-none-elf/release/example-gd32vf103
`
Compared to a binary from C from the gd32vf103inator project:
`riscv64-unknown-elf-size code.elf 
   text	   data	    bss	    dec	    hex	filename
   1002	      0	      6	   1008	    3f0	code.elf
`

I'm wondering if this has to do with my toolchain setup, but I don't have enough experience with Rust to determine this. Using readelf, it looks like the debug information is taking up a lot of space. This might be only an issue on my setup because I'm trying to use DFU, and it's balking.

**Comment by luojia65** [comment]
If I am correct,  only limited amount of sections (like `text` and `data`) would be loaded into the chip due to [memory mapping file at `gd32vf103-hal` library](https://github.com/gd32v-rust/gd32vf103-hal/blob/master/memory.x). 

The debug information are okay, because it's not located in these sections, thus won't be flashed into chip (actually debug information is intentionally kept at [library project configuration](https://github.com/gd32v-rust/gd32vf103-hal/blob/master/Cargo.toml#L33) even in `--release` optimization to help with debugging). If possible, this library configuration could be modified to not produce debug information, the ELF output would shrink but debugging process would be difficult (and the final binary size flashed into chip would not shrink).

**Comment by cculpepper** [comment]
I ended up figuring it out. It didn't have anything to do with the debug information, or anything that exotic. DFU was expecting a bin/hex file instead of an elf. Running objcopy -O binary on the built file converted it to a binary and let me upload it.

**Comment by luojia65** [comment]
Glad to see your reply. I am quarantined at home with not-so-fast Internet access, may reply slow. Best regards for us and embedded Rust!
